export {
  useCreateVehicleDiagnosticMutation,
  useDeleteVehicleDiagnosticMutation,
  useGetVehicleDiagnosticsQuery,
  useGetVehiclesQuery,
  useGetVehicleQuery,
  useGetVehicleModelSuggestionsQuery,
  useLazyGetVehicleQuery,
  useLazySearchVehiclesQuery,
  useAdoptSharedVehicleMutation,
  useUpdateVehicleMutation,
  useGetVehicleInspectionsQuery,
  useCreateVehicleInspectionItemMutation,
  useUpdateVehicleInspectionItemMutation,
  useDeleteVehicleInspectionItemMutation,
  useMarkVehicleInspectionsInOrderMutation,
  vehiclesApi,
} from './api/vehiclesApi';
export type {
  CreateVehicleDiagnosticRequest,
  GetVehiclesParams,
  UpdateVehicleRequest,
  VehicleCard,
  VehicleDiagnostic,
  VehicleDiagnosticFault,
  VehicleClient,
  VehicleHistoryStatus,
  VehicleListItem,
  VehicleListRepair,
  VehicleListResponse,
  VehicleRepairHistory,
  VehicleRepairSummary,
  VehicleSearchResult,
  VehicleSuggestion,
  VehicleModelSuggestion,
} from './model/types';
export type {
  CreateVehicleInspectionRequest,
  InspectionAction,
  InspectionItemStatus,
  InspectionUrgency,
  UpdateVehicleInspectionRequest,
  VehicleInspectionItem,
} from './model/inspection';
export {
  buildInspectionWorkTitle,
  inspectionActionLabels,
  inspectionStatusLabels,
  inspectionUrgencyLabels,
} from './model/inspection';
export { CarModelAutoComplete } from './ui/CarModelAutoComplete';
