export {
  useCreateVehicleDiagnosticMutation,
  useDeleteVehicleDiagnosticMutation,
  useGetVehicleDiagnosticsQuery,
  useGetVehiclesQuery,
  useGetVehicleQuery,
  useGetVehicleModelSuggestionsQuery,
  useLazyGetVehicleQuery,
  useLazySearchVehiclesQuery,
  useAdoptSharedVehicleMutation,
  useUpdateVehicleMutation,
  vehiclesApi,
} from './api/vehiclesApi';
export type {
  CreateVehicleDiagnosticRequest,
  GetVehiclesParams,
  UpdateVehicleRequest,
  VehicleCard,
  VehicleDiagnostic,
  VehicleDiagnosticFault,
  VehicleClient,
  VehicleHistoryStatus,
  VehicleListItem,
  VehicleListRepair,
  VehicleListResponse,
  VehicleRepairHistory,
  VehicleRepairSummary,
  VehicleSearchResult,
  VehicleSuggestion,
  VehicleModelSuggestion,
} from './model/types';
export { CarModelAutoComplete } from './ui/CarModelAutoComplete';
